# -*- coding: utf-8 -*-
"""tìm UCLN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tmCGgLhreOodcJIvqkwP8LosC4sEIxtX
"""

# Nhập hai số nguyên không âm a và b
a = abs(int(input("nhập a: ")))
b = abs(int(input("nhập b: ")))

# Xử lý trường hợp đặc biệt: cả a và b đều bằng 0
if a == 0 and b == 0:
    print("⚠️ Lỗi nhập: Cả a và b không được bằng 0 cùng lúc.")
# Xử lý trường hợp khi một trong hai số bằng 0
elif a == 0:
    print("UCLN của 2 số nguyên không âm:", b) # UCLN(0, b) = b
elif b == 0:
    print("UCLN của 2 số nguyên không âm:", a) # UCLN(a, 0) = a
# Trường hợp cả a và b đều khác 0, chúng ta sử dụng thuật toán Euclid
else:
    # Thuật toán Euclid: Lặp cho đến khi số thứ hai (b) bằng 0
    while b != 0:
        remainder = a % b  # Tìm số dư khi a chia cho b
        a = b              # Gán giá trị của b cho a
        b = remainder      # Gán số dư cho b
    print("UCLN của 2 số nguyên không âm:", a) # Khi b bằng 0, a chính là UCLN